package org.example.bot;

public enum UserCondition {
    WAITING_FOR_PASSWORD,
    WAITING_FOR_PASSWORD_COACH,
    REGISTERED,
    WAITING_FOR_PASSWORD_ADMIN,
    WAITING_FOR_NAME_STUDENT_ADMIN,
    WAITING_FOR_SURNAME_STUDENT_ADMIN,
    WAITING_FOR_AGE_STUDENT_ADMIN,
    WAITING_FOR_PASSWORD_STUDENT_ADMIN,
    WAITING_FOR_NAME_COACH_ADMIN,
    WAITING_FOR_SURNAME_COACH_ADMIN,
    WAITING_FOR_AGE_COACH_ADMIN,
    WAITING_FOR_EXPERIENCE_COACH_ADMIN,
    WAITING_FOR_PASSWORD_COACH_ADMIN,
}
